### ISSUE TITLE
Primordial Goo

### ISSUE THREAD

**Issue by MercuriusXeno** [MercuriusXeno/Goo#76]
ANOTHER goo type, but this one feels like it deserves a place among the ranks as the true "rarity" goo.

Diamonds and Netherite scrap have a sort of problem, they're relatively easy to acquire through conventional means.

You can construct obsidian fairly easily, you can get metal by decomposing regal, and you can get crystal fairly commonly in the world in the form of quartz, diorite, granite, ghast tears (a little less easy) and emeralds from villager trades are by far the most abusable vector.

The means of producing the two best materials in the game is, in a sense, more direct than I intended.

Primordial Goo is a goo type themed around being very old and, sort of directly, very rare.

You'll be able to obtain it from snails, once they exist, and that's the only way to get it, unless you're willing to sacrifice netherite scrap and diamonds.

Primordial goo's effect in world is intended to be very unique.

When primordial goo resolves on a splat, it dematerializes the world around it, forming what I'm calling a Glorb. Glorbs are big heterogeneous blobs that do not splat, and do not resolve. Intended as a sort of late game mechanic for the Goomancer to travel to exotic locations and directly dematerialize the world into the goo they need rather than relying strictly on machines.

**Comment by jackhardwareltd** [comment]
Is there some easy source of regal? The regal -> metal recipe doesn't seem that helpful in making scrap.

I'm not sure I agree with this as a solution to diamonds and scrap. Making diorite and granite not contain crystal and lowering the amount of crystal in emeralds seems like a good enough fix for diamonds, and adding royal and/or a large amount of decay to scrap would complicate the recipe enough to make it harder. I don't love the idea of having to hunt a rare mob to be able to get the goo for these, because they're already rare, so I'd rather just hunt for them directly. So balancing the rarity and the amount of goo such a mob would give sounds tricky.

I'm trying to automate crystal production in my survival world, and right now it's mostly waiting for honeycombs for gaskets, because it needs a lot of goo machines. For reference as to current balance, it'll take me 576 cobble, 8 ice, 12 slime, 20 netherwart to make 1 diamond. Most of these are made a lot easier by automation from other mods, but it still doesn't feel like it's going to be too easy.

**Comment by MercuriusXeno** [comment]
1) Bees make regal. Have a look at honeycomb.
2) Granite and diorite contain quartz and quartz is crystal.
3) I'm not opposed to giving a mixer recipe for primordial at an extremely lossy rate as a direct answer to your concern about it being difficult to acquire. The point is to increase the complexity with something specific to the rarity of those materials.
Crystal doesn't do that, adjusting numbers by itself doesn't change complexity, and the point isn't that you can make diorite into diamonds. It's that you can make diamonds from diorite *alone*. Or lapis *alone*. or quartz *alone*. Taking crystal out of things that legitimately contain it isn't an answer I'm receptive to.

**Comment by MercuriusXeno** [comment]
So, proposal:
Mix 32 weird and 32 crystal for 1 primordial.

My intended primordial gating on scrap and diamonds is, perhaps surprisingly, to put 1 mB of primordial on them.

So if you're not willing to play the mob game, you can still access these things in a way that's automatic.

**Comment by MercuriusXeno** [comment]
Alternatively drop those exchange rates to 8, 8 : 1
And put 4 mB of primordial on them. That way the price in weird and crystal is proportionally the same but the numbers don't feel quite as weird.

**Comment by Entoarox** [comment]
@jackhardwareltd The goal is that the mob spawns rarely, because once you get it, you have it from then on, the whole production chain Xeno has in his head (With feedback from me and others on discord) is designed so that primordial goo is tier 4 in the goo crafting tiers, locking the 2 most valuable resources in vanilla at tier 4 of a mods crafting progression is more then reasonable, especially when you take into account that they are currently accessible at tier 1 without much effort.

Right now, Xeno has to be incredibly specific with what items can have Crystal goo, and how much - just adding 1mb of Primordial to diamonds means that Xeno no longer has to be that careful, because primordial is, by design, a tier 4 material in goo, and thus not something you can get in large quantities before having a big goo setup.

A lot of discussion has gone into how this should happen, and even then *the idea has not been implemented yet*
Once Xeno does implement it, he may find that the existing spawn chances for the mob, or their Primoridial production do not match his intent, and then he can simply *make them more or less rare, and drop more or less Primordial*.

The goal of primordial is allowing Xeno to be more free with the Crystal, Metal and Regal goo types, which currently, by necessity, he has to be incredibly strict about to ensure that MC's most end-game materials *remain* end-game materials.

**Comment by MercuriusXeno** [comment]
This is done
