### ISSUE TITLE
Energetic goo doesn't break coal ore

### ISSUE THREAD

**Issue by Pecant-Pie** [MercuriusXeno/Goo#98]
I am not sure if this is an intended feature or not, but energetic goo splats are not breaking coal ore when I was throwing it around underground. Since energetic goo breaks redstone ore and iron ore I would expect it to be able to break coal. The mods I am using in that world are: AEquivaleo-0.1.16-ALPHA, Botania-1.16.3-409, Curios-Forge-1.16.3-4.0.2.0, Goo-1.16.3-0.8.0.2, JEI-1.16.3-7.6.0.49, MouseTweaks-2.13-mc1.16.2, and Patchouli-1.16.2-47.

**Comment by MercuriusXeno** [comment]
It's a bug that it breaks redstone; energetic is supposed to leave behind any block that would be better to break with fortune, but the redstone issue is that activated redstone ore qualifies as a different block which causes weirdness.

I'll leave this open because the redstone thing is a bug, but the coal being left behind is intentional.

**Comment by MercuriusXeno** [comment]
Changing energetic to not "optimize", as it's bound to cause this sort of confusion more and more. It's not intuitive, even if it's helpful.

**Comment by MercuriusXeno** [comment]
Energetic now doesn't care if a block could be broken with fortune to be more efficient. It just blows up, as one expects.
